language: php

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.composer/cache/files

# 本项目要求 PHP 7+, 考虑到 PHP 版本命名的规律，这里均以 7.x.0 版本进行测试
# 且考虑到该项目今后会封装成 Laravel 扩展包，所以针对特定 PHP 版本进行测试
# 7.0 for Laravel 5.5
# 7.1.3 for Laravel 5.6 - 5.8
# 7.2 for Laravel 6.x
php:
  - 7.0.0
  - 7.1.3
  - 7.2.0
  - 7.3.0

before_install:
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/xdebug.ini
  - phpenv config-rm xdebug.ini
  - composer global require hirak/prestissimo --update-no-dev

install: travis_retry composer install --no-interaction --prefer-dist

before_script: phpenv config-add ~/xdebug.ini

script:
  - composer show
  - vendor/bin/phpunit -v

after_success:
  - php vendor/bin/php-coveralls

notifications:
  email: false